exclude: 'docs|node_modules|migrations|.git|.tox'

repos:
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.213'
  hooks:
    - id: ruff
      args: ["--force-exclude"]

- repo: https://github.com/crate-ci/typos
  rev: v1.13.6
  hooks:
    - id: typos
