[tool.poetry]
name = "fastapi_book_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = ">=0.77.1"
pydantic = {extras = ["dotenv"], version = "^1.9.0"}
uvicorn = {extras = ["standart"], version = "^0.17.6"}
ormar = {extras = ["postgresql"], version = "^0.11.0"}
alembic = "^1.7.7"
fastapi-pagination = {extras = ["ormar"], version = "^0.9.3"}
orjson = "^3.6.8"
aioredis = "^2.0.1"
httpx = "^0.22.0"
meilisearch = "^0.18.3"
prometheus-fastapi-instrumentator = "^5.8.1"
uvloop = "^0.16.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.5.12"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.flake8]
ignore = [
    # Whitespace before ':' ( https://www.flake8rules.com/rules/E203.html )
    "E203"
]
max-line-length=88
max-complexity = 15
select = "B,C,E,F,W,T4,B9"
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "fastapi_book_server/app/alembic/*",
    # The old directory contains Flake8 2.0
]

[tool.isort]
profile = "black"
only_sections = true
force_sort_within_sections = true
lines_after_imports = 2
lexicographical = true
sections = ["FUTURE", "STDLIB", "BASEFRAMEWORK", "FRAMEWORKEXT", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_baseframework = ["fastapi",]
known_frameworkext = ["starlette",]
src_paths = ["fastapi_book_server"]
